"""crear tabla jobs

Revision ID: 2e8a7c990ec1
Revises: 
Create Date: 2026-05-25 15:39:14.991448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8a7c990ec1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fase_actual', sa.String(), nullable=True),
    sa.Column('nombre_dataset', sa.Text(), nullable=False),
    sa.Column('var_tiempo', sa.String(), nullable=True),
    sa.Column('metricas_candidatas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrica_seleccionada', sa.String(), nullable=True),
    sa.Column('granularidad_s', sa.Integer(), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ruta_csv_entrada', sa.Text(), nullable=False),
    sa.Column('ruta_csv_fuzzy', sa.Text(), nullable=True),
    sa.Column('ruta_csv_reglas', sa.Text(), nullable=True),
    sa.Column('ruta_informe_md', sa.Text(), nullable=True),
    sa.Column('error_mensaje', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
